# Generated by Django 5.2.6 on 2025-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='descript',
            field=models.TextField(blank=True),
        ),
    ]
